from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_welcomeWindow(object):
    def setupUi(self, welcomeWindow):
        welcomeWindow.setObjectName("welcomeWindow")
        welcomeWindow.resize(800, 601)
        self.centralwidget = QtWidgets.QWidget(parent=welcomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.enterPassLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.enterPassLabel.setGeometry(QtCore.QRect(10, 130, 501, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        self.enterPassLabel.setFont(font)
        self.enterPassLabel.setObjectName("enterPassLabel")
        self.proceedButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.proceedButton.setGeometry(QtCore.QRect(10, 220, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.proceedButton.setFont(font)
        self.proceedButton.setObjectName("proceedButton")
        self.inputField = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.inputField.setGeometry(QtCore.QRect(10, 170, 781, 41))
        self.inputField.setObjectName("inputField")
        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(10, 10, 781, 53))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(False)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.sub_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.sub_title.setGeometry(QtCore.QRect(10, 60, 781, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        self.sub_title.setFont(font)
        self.sub_title.setObjectName("sub_title")
        self.self_promo = QtWidgets.QLabel(parent=self.centralwidget)
        self.self_promo.setGeometry(QtCore.QRect(10, 510, 781, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.self_promo.setFont(font)
        self.self_promo.setObjectName("self_promo")
        welcomeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=welcomeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        welcomeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=welcomeWindow)
        self.statusbar.setObjectName("statusbar")
        welcomeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(welcomeWindow)
        QtCore.QMetaObject.connectSlotsByName(welcomeWindow)

    def retranslateUi(self, welcomeWindow):
        _translate = QtCore.QCoreApplication.translate
        welcomeWindow.setWindowTitle(_translate("welcomeWindow", "MainWindow"))
        self.enterPassLabel.setText(_translate("welcomeWindow", "Enter Master Password To Proceed"))
        self.proceedButton.setText(_translate("welcomeWindow", "Proceed"))
        self.title_label.setText(_translate("welcomeWindow", "Password Manager"))
        self.sub_title.setText(_translate("welcomeWindow", "All in One Password Container"))
        self.self_promo.setText(_translate("welcomeWindow", "Developed By : Anshu Sharma"))
